import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <meta
        property="og:image"
        content="https://www.pngkit.com/png/detail/186-1867486_pandablindfold-discord-emoji-admiral-bahroo-emotes.png"
      ></meta>
      <div className={styles.container}>
        <Head>
          <title>Hydro Web</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to{" "}
            <a href="https://fb.com/hungdarealesttt">Hydro Facebook</a>
          </h1>
        </main>
      </div>
    </>
  );
};

export default Home;
